Feature/18
Murasya/team14 pull request #21
Opened 2022-06-18 03:01 UTC by Yuki992411

* スキーマ定義
* DB接続に必要なCRUD機能の実装

2022-06-18 03:08 UTC, Yuki992411 commented
テストファイルは作ってないです．．
代わりに動作確認として，`main.dart`を以下のように変えて，実機(Androidのタブレット)で動きを確かめました．
出力はConsoleです．

```dart
import 'package:flutter/material.dart';
import 'spot.dart';
import 'spotProvider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  SpotProvider sp = SpotProvider();

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.

      Spot spot = Spot(
        _counter,
        'team14',
        27.7,
        'position',
        'This is memo.',
        'created time',
        'updated time',
      );
      sp.insert(spot);
      spot.memo = 'This is second memo.';
      spot.id = _counter - 2;
      sp.update(spot);
      sp.selectAll().then((spots) {
        for (var spot in spots) {
          spot.dumpAllColumns();
        }
      });
      sp.delete(spot.id);
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    sp.open();
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

2022-06-18 03:11 UTC, Yuki992411 commented
あと，時間ですがこちらはまだ実装していません．
どんな感じで実装しましょうか？
`insert`や`update`内で，時間を取得しstringに変えるように設計するか，Spotクラスに，時間をstringに変更するメソッドだけ追加するのか．
助言お願いします．

2022-06-18 05:25 UTC, Murasya reviewed
コードレビューはこんな感じです！細かい点も多いですが、対応よろしくお願いします

現状だとidがアプリを起動させるたびに被ってしまっているので、対応を考え中です。

2022-06-18 05:25 UTC, Murasya commented on lib/spotProvider.dart
> +
いちいちopenするのは面倒なので、コンストラクタでopen呼び出しときましょう
```
SpotProvider() {
  open();
}
```

2022-06-18 05:59 UTC, Murasya commented
すみません！追記です。
idを使わずにinsertしたいので、spot.dartを以下のように変更をお願いします。
- nullableにする（int? id)
- コンストラクタからidを消去
- toMapからidを消去

2022-06-18 06:48 UTC, Yuki992411 commented on lib/spot.dart
> +  String gpsPosition;
了解です．こちらは，`latitude`，`longitude`で分けようと思います．

2022-06-18 06:50 UTC, Yuki992411 commented on lib/spotProvider.dart
> +
了解です．
ただ，`close`はいつ呼び出しますか？デストラクタはない？みたいですが...

2022-06-18 11:44 UTC, Yuki992411 commented on lib/spotProvider.dart
> +    List<Map<String, Object?>> maps = await db.query(tableName, columns: [
ここ，戻り値が`Future<List<Spot>>`なので，エラーが出てしまいます．．

2022-06-18 11:49 UTC, Murasya commented on lib/spotProvider.dart
> +    List<Map<String, Object?>> maps = await db.query(tableName, columns: [
final maps = await db.query(
      tableName,
      orderBy: 'id DESC',
    );

    if (maps.isEmpty) return [];

    return maps.map((map) => Spot.fromMap(map)).toList();

コピペミスりました！

2022-06-18 11:51 UTC, Murasya commented on lib/spotProvider.dart
> +
closeは特に意識する必要ないですが、書くならstateful widgetのdisposeをオーバーライドしてそこに書くといいと思います

2022-06-18 11:54 UTC, Yuki992411 commented on lib/spotProvider.dart
> +    List<Map<String, Object?>> maps = await db.query(tableName, columns: [
なるほど！
Futureクラスを返さないといけないのかと思ってました
ありがとうございます！

2022-06-19 00:26 UTC, Murasya requested changes
申し訳ない！コンストラクタで呼び出すと、呼び出すタイミングによってはdb未定義のエラーになっちゃうので、仕様変えます
具体的にはinsertとか呼び出すタイミングでopenを毎回呼び出します。

openしまくってもsqfliteが内部でいい感じにしてくれてるはずなので、これでお願いします。

2022-06-19 00:26 UTC, Murasya commented on lib/spotProvider.dart
> +
申し訳ない！コンストラクタで呼び出すと、呼び出すタイミングによってはdb未定義のエラーになっちゃうので、仕様変えます

2022-06-19 00:26 UTC, Murasya commented on lib/spotProvider.dart
> +  Future _open() async {
Future<Database> _open() async {
に変更

2022-06-19 00:26 UTC, Murasya commented on lib/spotProvider.dart
> +    db = await openDatabase(join(dbFilePath, dbName), version: 1,
return await openDatabase(join(dbFilePath, dbName), version: 1,

に変更

2022-06-19 00:26 UTC, Murasya commented on lib/spotProvider.dart
> +    return await db.insert(tableName, spot.toMap());
insert, selectAll, update, delete, closeのdbを呼び出す部分で
```
final db = await _open();
```

2022-06-19 00:26 UTC, Murasya commented on lib/spotProvider.dart
> +  late Database db;
削除

2022-06-19 01:51 UTC, merged