Feature/55
Murasya/team14 pull request #65
Opened 2022-06-27 16:17 UTC by yuta-tech

share referenceの実装

2022-06-27 17:05 UTC, Yuki992411 requested changes

2022-06-27 19:54 UTC, Yuki992411 requested changes

2022-06-27 19:56 UTC, Yuki992411 commented
すみません．色々見ていたらこんなに長くなってしまいました．
一応，プッシュ前に黄色い波線（警告）がないことを確認お願いします．
`print`やタイポの警告は大丈夫です．

2022-06-27 20:12 UTC, Yuki992411 requested changes

2022-06-27 20:12 UTC, Yuki992411 commented on lib/views/select_template_page.dart
> +                                      if (defaultTemplate !=
ここのif -elseですが，
```dart
if (action == '削除') {
  _deleteTemplate(snapshot.data![index].id!);
} else if (action == 登録) ...
```
として，全て，`_deleteTemplate`に入れてみてください，調べてみたところ，非同期の処理のエラーハンドリングは`runZonedGuarded`がいいみたいです．↓こんな感じです
```dart
Future<void> _deleteTemplate(int id) async {
    Map<int, String> warningDialogMap = {
      1: 'このテンプレートはデフォルトに登録されています',
      2: 'このテンプレートはメモで使われています',
    };
    int errorCode = 0;
    runZonedGuarded(() async {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      if (id == prefs.getInt('defaultTemplate')) {
        errorCode = 1;
        throw 'This template is registered as default';
      }
      await mtp.delete(id);
      setState(() {
        templateList = mtp.selectAll();
      });
    }, (e, s) {
      print('[Error] $e');

      String errorMsg =
          errorCode == 1 ? warningDialogMap[1]! : warningDialogMap[2]!;
      showDialog(
        context: context,
        builder: (_) {
          return WarningDialog(
            text: errorMsg,
          );
        },
      );
    });
  }
```

2022-06-28 00:46 UTC, yuta-tech commented on lib/views/memo_list_page.dart
> +                                onTapContent(
これバグの原因が分かんなくて弄り倒しちゃったときのやつです...  
消しておきます！

2022-06-28 03:29 UTC, Yuki992411 requested changes
たくさんの修正ありがとうございます．
あと3点，お願いします！
一応，リフォーマットは1ファイルだけでしたが，念のためコミット対象のファイル全て確認をお願いします．
`pubspec`は不要だと思います

2022-06-28 03:29 UTC, Yuki992411 commented on lib/views/create_template_page.dart
> +  // テンプレid
スコープは極力小さくしたいので，`onSubmit`内で宣言をお願いします！
`late`修飾子はなくて大丈夫です

2022-06-28 03:29 UTC, Yuki992411 commented on lib/views/memo_list_page.dart
> +  late DefaultTemplateProvider dtp = DefaultTemplateProvider();
`late`なくて大丈夫です

2022-06-28 03:29 UTC, Yuki992411 commented on lib/views/select_template_page.dart
> +      errorCode == 1 ? warningDialogMap[1]! : warningDialogMap[2]!;
ここで，リフォーマットがかかってしまったので，リフォーマットをお願いします

2022-06-28 05:32 UTC, Yuki992411 approved these changes

2022-06-28 05:33 UTC, merged